<?php echo $block->getChildHtml('create_ticket');?>
<script type="text/javascript">
    require([
        "jquery",
        "tinymce",
        "Magento_Ui/js/modal/modal"
    ], function($){
        var createTicketSlide = $('#zendesk-ticket-form').modal({
            type: 'slide',
            title: $.mage.__('Create New Ticket'),
            buttons: [
                {
                    text: 'Cancel',
                    click: function () {
                        this.closeModal();
                    }
                }
            ]
        });
        $('.zendesk-create-ticket').on('click', function() {
            createTicketSlide.modal('openModal');
        });
    });
</script>
