<?php
/**
 * Product list toolbar
 *
 * @var $block \Althea\ProductFilter\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()): ?>
	<div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
		<button
			type="button"
			class="action filter-toggle"
			data-trigger="filter"
			style="display: none;">
			<span><?php echo __('Filter'); ?></span>
		</button>
		<button
			type="button"
			class="filter-toggle-full">
			<span><?php echo __('Filter'); ?></span>
		</button>
		<!-- althea: disable sorter for bestsellers -->
<!--		--><?php //if ($block->isExpanded()): ?>
<!--			--><?php //include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
<!--		--><?php //endif; ?>

		<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

		<?php if ($block->isExpanded()): ?>
			<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
		<?php endif; ?>

		<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

		<?php echo $block->getPagerHtml() ?>
	</div>
<?php endif ?>