<?php /* @var Althea\Checkout\Block\Onepage $block */ ?>
<style>
    .centered {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        min-width: 300px;
        text-align: center;
    }
</style>
<div id="mobile-checkout-redirect-molpay-seamless" class="centered">
    <h1>Please click to proceed with payment</h1>
    <form action="<?php echo $block->getUrl('seamless'); ?>" method="post" id="seamless" role="molpayseamless">
        <input type="hidden" name="cart_id" value="<?php echo $block->getCheckoutSession()->getQuoteId(); ?>"/>
        <input type="hidden" name="current_email" value=""/>
        <input type="hidden" name="payment_options"
               value="<?php echo $block->getCheckoutSession()->getAltheaCheckoutPaymentChannel(); ?>"/>
        <button type="button" id="seamless-form-submit" class="action primary checkout">Pay Now</button>
    </form>
</div>
<script type="text/x-magento-init">
    {
        "#mobile-checkout-redirect-molpay-seamless": {
            "molpaySeamless": {}
        }
    }
</script>
<script>
    window.checkoutConfig     = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
    // Create aliases for customer.js model from customer module
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData       = window.checkoutConfig.customerData;
</script>