<?php
/** @var \Althea\Nexmo\Block\Request $block */
?>
<div class="nexmo-request-verification container">
    <div class="row">
        <form class="form-inline" action="<?php echo $block->getUrl('precheckout/verification/requestPost'); ?>"
              method="post">
            <div class="form-group">
                <label class="sr-only" for="intlCode"><?php echo __('Country Code')?></label>
                <select class="form-control" id="intlCode" name="countryCode"></select>
            </div>
            <div class="form-group">
                <label class="sr-only" for="phoneNo"><?php echo __('Your phone number')?></label>
                <input class="form-control" id="phoneNo" class="phoneNo" type="text" placeholder="<?php echo __('Your phone number')?>" name="phoneNo"
                       required/>
            </div>
            <div class="form-group">
                <div class="actions-toolbar">
                    <button class="action" type="submit"><?php echo __('REQUEST CODE')?></button>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#intlCode": {
            "nexmoVerificationRequest": {
                "data": <?php echo $this->getCountryJson(); ?>
            }
        }
    }
</script>