<?php
/* @var \Althea\Nexmo\Block\Verify $block */
?>
<div class="nexmo-verify-verification container">
    <div class="row">
        <form class="form-inline" action="<?php echo $block->getUrl('precheckout/verification/verifyPost'); ?>"
              method="post">
            <input type="hidden" name="request_id" value="<?php echo $block->getRequest()->getParam('request_id'); ?>"/>

            <div class="form-group">
                <label class="sr-only" for="code"><?php echo __('Verification Code') ?></label>
                <input class="form-control code" type="text" id="code" name="code"
                       placeholder="<?php echo __('Verification Code') ?>"/>
            </div>
            <div class="form-group">
                <div class="actions">
                    <a href="<?php echo $block->getUrl('precheckout/verification/request'); ?>" class="action">
                        <?php echo __('Back') ?>
                    </a>
                    <button class="action primary" type="submit"><?php echo __('Verify') ?></button>
                </div>
            </div>
        </form>
    </div>
</div>
