<?php
/**
 * Created by PhpStorm.
 * User: alvin
 * Date: 26/07/2017
 * Time: 2:57 PM
 */

namespace Althea\Nexmo\Block;

use Magento\Framework\UrlInterface;
use Magento\Framework\View\Element\Template;

class Request extends Template {

	public function _prepareLayout()
	{
		return parent::_prepareLayout(); // TODO: Change the autogenerated stub
	}

	public function getCountryJson()
	{
		$data         = [];
		$options      = [
			"ssl" => [
				"verify_peer"      => false,
				"verify_peer_name" => false,
			],
		];
		$currentStore = $this->_storeManager->getStore();
		$fileUrl      = sprintf("%s%s", $currentStore->getBaseUrl(UrlInterface::URL_TYPE_MEDIA), 'althea/data/countries.json');
		$str          = file_get_contents($fileUrl, null, stream_context_create($options));
		$str          = (!$str) ? [] : json_decode($str, true);

		foreach ($str as $country) {

			$data[] = [
				'id'   => $country['code'],
				'text' => sprintf("%s (%s)", $country['name'], $country['dial_code']),
			];
		}

		return json_encode($data, JSON_HEX_APOS);
	}

}