<?php /** @var TemplateMonster\SocialLogin\Block\Account\SocialLogin $block */ ?>
<div class="row">
    <div class="col-md-8 col-md-preffix-2">
        <div class="block block-social-login">
            <div class="block-title">
                <strong id="block-social-login-heading" role="heading"
                        aria-level="2"><?php echo __('Login Using Social Accounts') ?></strong>
            </div>
            <div class="block-content" aria-labelledby="block-social-login-heading">
                <p>
                    <?php echo __('You can login using one of the social accounts provided below.') ?>
                </p>
                <?php if ($block->hasProviders()): ?>
                    <div class="actions-toolbar">
                        <?php foreach ($block->getProviders() as $provider): ?>
                            <div class="full">
                                <a href="#" data-post='<?php echo $block->getGrantPostData($provider) ?>'
                                   class="<?php echo $block->getProviderCode($provider) ?> action">
                                    <i class="fa fa-<?php echo $block->getProviderCode($provider) ?>"></i>
                                    <span
                                        class="label"><?php echo __('Sign in with') . ' ' . $block->getProviderLabel($provider) ?></span>
                                </a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>