<?php
$formHtml = $block->getFormHtml();
$actionHtml = $block->getActionHtml();
if (\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\Registry')->registry(
        'trackingimport_xml_action_warning'
    ) !== null
) {
    echo '<div id="messages"><ul class="messages"><li class="error-msg"><ul><li><span>' . \Magento\Framework\App\ObjectManager::getInstance(
        )->get('Magento\Framework\Registry')->registry('trackingimport_xml_action_warning') . '. ' . __(
            'Please fix and re-save profile.'
        ) . '</span></li></ul></li></ul></div>';
}
?>
<div class="entry-edit">
    <?php echo $formHtml; ?>
    <fieldset class="fieldset admin__fieldset fieldset-wide" style="padding-bottom:0">
        <legend class="admin__legend legend">
            <span><?php echo __('Import Actions') ?></span>
        </legend>
    </fieldset>
    <?php echo $actionHtml; ?>
</div>
<style type="text/css">
    #grid_action label {
        width: 100px;
    }

    #grid_action .label {
        width: 110px;
    }

    #grid_action .scalable {
        width: 100%;
        padding-left: 0 !important;
        padding-right: 0 !important;
    }
</style>
<?php echo $block->getChildHtml('form_after'); ?>
