<?php
// @codingStandardsIgnoreFile
?>
<form <?php echo true === $block->getNeedHide() ? 'style="display:none"': ''?> class="form zendesk-ticket"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl($block->getSubmitRoute(), ['_current' => true]); ?>"
      id="zendesk-ticket-form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <div><input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>" /></div>
    <?php if ($this->getTicket()): ?>
            <input type="hidden" name="ticket_id" value="<?php echo $block->getTicket()->getId() ?>">
        <?php endif; ?>
        <?php if ($this->getNeedSubject()): ?>
            <div class="subject-field">
                <label for="ticket_subject"><?php echo __('Subject'); ?></label>
                <input type="text" id="ticket_subject" name="subject"/>
            </div>
        <?php endif; ?>
        <div class="field comment required">
            <div class="control">
                <textarea name="comment" style="width:100%" title="comment" id="comment" class="input-text" cols="5" rows="3"></textarea>
            </div>
        </div>

    <script type="text/javascript">
        require([
            "tinymce",
            "jquery"
        ], function(tinyMCE, $){
            $(document).ready(function(){
                tinyMCE.init({
                    mode: "exact",
                    elements: "comment",
                    theme: "advanced",
                    plugins: "inlinepopups,style,layer,save,advhr,autolink,iespell,media,directionality,noneditable,visualchars,nonbreaking,xhtmlxtras",
                    theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,cite,hr",
                    theme_advanced_buttons2: "",
                    theme_advanced_buttons3: "",
                    theme_advanced_buttons4: "",
                    theme_advanced_toolbar_location: "top",
                    theme_advanced_toolbar_align: "left",
                    theme_advanced_path_location: "",
                    extended_valid_elements: "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
                    theme_advanced_resize_horizontal: 'true',
                    theme_advanced_resizing: 'true',
                    apply_source_formatting: 'true',
                    convert_urls: 'false',
                    fullpage_default_fontsize: "14px"
                });
            });
        });
    </script>
    <div class="zendesk-editor--attachments" id="attachment_container">
    </div>
    <div class="actions-toolbar">
        <div class="zendesk-editor--attachment">
            <button type="button" id="zendesk_upload_button" class="zendesk-editor--item" aria-label="undefined">
                <svg id="attachment" viewBox="0 0 14 14">
                    <path fill="none" stroke="currentColor" d="M6 4.6v5c0 .6.5 1.1 1.1 1.1s1.1-.5 1.1-1.1V2.7C8.2 1.5 7.2.5 6 .5s-2.2 1-2.2 2.2v7.5c0 1.8 1.5 3.3 3.3 3.3s3.3-1.5 3.3-3.3V4.6" stroke-linecap="round" stroke-linejoin="round"></path>
                </svg>
            </button>
            <script type="text/javascript">
                require([
                    "jquery"
                ], function(jQuery) {
                    function handleFileSelect(evt) {
                        for (var i = 0, f; f = evt.target.files[i]; i++) {
                            var reader = new FileReader();
                            reader.onload = (function (file) {
                                return function (e) {
                                    var container = document.createElement('div');
                                    jQuery(container).addClass('zendesk-editor--attachment');
                                    jQuery(container).addClass('zendesk-editor--uploaded');

                                    var removeDiv = document.createElement('div');
                                    jQuery(removeDiv).addClass('zendesk-editor--remove-attachment');
                                    jQuery(removeDiv).click(function(el){
                                        jQuery(el.target).parent().remove();
                                        jQuery(evt.target).remove();
                                    });
                                    container.appendChild(removeDiv);

                                    var textDiv = document.createElement('div');
                                    jQuery(textDiv).addClass('zendesk-editor--text-wrapper');

                                    var fileUrl = document.createElement('a');
                                    fileUrl.href = '';
                                    fileUrl.innerHTML = file.name;
                                    fileUrl.title = file.name;
                                    textDiv.appendChild(fileUrl);

                                    var fileType = document.createElement('p');
                                    jQuery(fileType).addClass('zendesk-editor--filetype');
                                    fileType.innerHTML = file.type;
                                    textDiv.appendChild(fileType);

                                    var fileSize = document.createElement('p');
                                    jQuery(fileSize).addClass('zendesk-editor--filesize');
                                    fileSize.innerHTML = file.size;
                                    textDiv.appendChild(fileSize);

                                    if (file.type.match('image.*')) {
                                        jQuery(container).addClass('zendesk-editor--image');

                                        var image = document.createElement('img');
                                        jQuery(image).addClass('zendesk-editor--attachment-image');
                                        image.src = e.target.result;
                                        container.appendChild(image);
                                    } else {
                                        var cornerDiv = document.createElement('div');
                                        jQuery(cornerDiv).addClass('zendesk-editor--corner');
                                        container.appendChild(cornerDiv);
                                        jQuery(textDiv).show();
                                    }
                                    container.appendChild(textDiv);
                                    jQuery('#attachment_container').append(container, null);
                                };
                            })(f);
                            reader.readAsDataURL(f);
                        }
                    }
                    jQuery('#zendesk_upload_button').click(function () {
                        var inputFile = document.createElement('input');
                        inputFile.type = 'file';
                        inputFile.name = 'file[]';
                        jQuery(inputFile).hide();
                        jQuery(inputFile).on('change', handleFileSelect);
                        jQuery('#attachment_container').append(inputFile, null);
                        jQuery(inputFile).click();
                    });
                });
            </script>
        </div>
        <?php if (!$block->hasNeedDisableSubmit()): ?>
        <div class="primary submit">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
        <?php endif; ?>
    </div>
</form>
