<?php
$columnNumber = 3;
?>

<?php if ($posts = $this->getPosts()) : ?>
    <div class="block widget blog-posts">
        <div class="block-title">
            <strong><?php echo __('Latest Posts') ?></strong>
        </div>
        <div class="block-content">
            <div class="post-items">
            <?php foreach ($posts as $post): ?>
                <div class="post-item">
                    <div class="item-wrapper">
                        <!-- Image -->
                        <?php if ($image = $post->getImage()): ?>
                        <div class="post-image">
                            <a href="<?php echo $this->getPostUrl($post); ?>"><img src="<?php echo $image ?>" /></a>
                        </div>
                        <?php endif; ?>

                        <!-- Title -->
                        <div class="post-title">
                            <h3>
                                <a href="<?php echo $this->getPostUrl($post); ?>"><?php echo $post->getTitle(); ?></a>
                            </h3>
                        </div>

                        <!-- Short Description -->
                        <div class="post-short-content">
<!--                            --><?php //echo $block->filterContent($post->getShortContent()); ?>
                            <?php $small_getDescription = strip_tags($block->filterContent($post->getShortContent()));
                            if (strlen($small_getDescription) < 70) echo($small_getDescription);
                            else { echo mb_substr($small_getDescription, 0, 70,'UTF-8');} ?>
                            <a href="<?php echo $this->getPostUrl($post); ?>" class="post-link">
                                <?php /* @escapeNotVerified */ echo __('...'); ?>
                            </a>
                        </div>

                        <!-- Metadata -->
                        <div class="post-data">
                            <?php if ($post->getCommentsEnabled()) : ?>
                                <span class="post-comments">
                                    <a href="<?php echo $this->getPostUrl($post); ?>#post-comments">
                                        <span class="count">
                                            <?php echo $post->getApprovedComments()->count(); ?>
                                        </span>
                                    </a>
                                </span>
                            <?php endif; ?>
                            <span class="create-date">
                                <time><?php echo $block->formatDate($post->getCreationTime(), 2, false);?></time>
                            </span>
                            <?php if ($author = $post->getAuthor()): ?>
                                <span class="post-author">
                                    <span class="label"><?php echo __('by '); ?></span>
                                    <span class="author"><?php echo $author; ?></span>
                                </span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>