<?php
/**
 * Template for filter items block
 *
 * - based on Smile-SA/elasticsuite for reference
 *
 * @var $block \Althea\CatalogSearch\Block\Navigation\FilterRenderer
 */
?>
<?php
$datascope = $this->getFilter()->getRequestVar() . 'Filter';
?>
<?php if (!empty($filterItems)) : ?>
	<div data-bind="scope: '<?php echo /* @escapeNotVerified */ $datascope; ?>'">
		<!-- ko template: getTemplate() --> <!-- /ko -->
	</div>

	<script type="text/x-magento-init">
    {"*" : {"Magento_Ui/js/core/app": {"components": {"<?php echo /* @escapeNotVerified */ $datascope; ?>": <?php echo /* @escapeNotVerified */ $this->getJsLayout(); ?>}}}}
</script>

<?php endif; ?>