<?php
/**
 * Template for filter items block
 *
 * - based on Smile-SA/elasticsuite for reference
 *
 * @var $block \Althea\CatalogSearch\Block\Navigation\FilterRenderer
 */
?>

<ol class="items">
	<?php foreach ($filterItems as $filterItem): ?>
		<li class="item">
			<?php if ($filterItem->getCount() > 0): ?>
				<a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
					<?php if ($this->isMultipleSelectEnabled()) : ?>
						<input type="checkbox" onclick="this.parentNode.click();" <?php if($filterItem->getIsSelected()) : ?>checked<?php endif; ?> />
					<?php endif; ?>
					<?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
					<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
						<span class="count">
                            <?php /* @escapeNotVerified */ echo $filterItem->getCount()?>
							<span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?>
	                        <?php /* @escapeNotVerified */ echo __('item')?>
                        <?php else:?>
	                        <?php /* @escapeNotVerified */ echo __('items') ?>
                        <?php endif;?></span></span>
					<?php endif; ?>
				</a>
			<?php else:?>
				<?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
				<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
					<span class="count">
                        <?php /* @escapeNotVerified */ echo $filterItem->getCount()?>
						<span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?>
	                        <?php /* @escapeNotVerified */ echo __('item')?>
                        <?php else:?>
	                        <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?>
                        </span>
                    </span>
				<?php endif; ?>
			<?php endif; ?>
		</li>
	<?php endforeach ?>
</ol>
